# trigger
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: sh
    args:
      - -c
      - |
        pack build --build-arg MONGODB_URI=$$MONGODB_URI --build-arg NEXTAUTH_SECRET=$$NEXTAUTH_SECRET -t gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA .
#    args: ['build', '--build-arg', 'MONGODB_URI=$$MONGODB_URI', '--build-arg', 'NEXTAUTH_SECRET=$$NEXTAUTH_SECRET', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
#    env:
#      - 'MONGODB_URI=${_MONGODB_URI}'
#      - 'NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}'
    secretEnv:
      - 'MONGODB_URI'
      - 'NEXTAUTH_SECRET'
      # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'self-hosted-docker-demo'
      - '--update-env-vars'
      - 'MONGODB_URI=projects/$PROJECT_NUMBER/secrets/MONGODB_URI/versions/latest,NEXTAUTH_SECRET=projects/$PROJECT_NUMBER/secrets/NEXTAUTH_SECRET/versions/latest,GITHUB_PERSONAL_ACCESS_TOKEN=projects/$PROJECT_NUMBER/secrets/GITHUB_PERSONAL_ACCESS_TOKEN/versions/latest'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    secretEnv:
      - 'MONGODB_URI'
      - 'GITHUB_PERSONAL_ACCESS_TOKEN'
      - 'NEXTAUTH_SECRET'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/MONGODB_URI/versions/latest
      env: 'MONGODB_URI'
    - versionName: projects/$PROJECT_NUMBER/secrets/GITHUB_PERSONAL_ACCESS_TOKEN/versions/latest
      env: 'GITHUB_PERSONAL_ACCESS_TOKEN'
    - versionName: projects/$PROJECT_NUMBER/secrets/NEXTAUTH_SECRET/versions/latest
      env: 'NEXTAUTH_SECRET'
#substitutions:
#  _MONGODB_URI: $MONGODB_URI
#  _NEXTAUTH_SECRET: $NEXTAUTH_SECRET
options:
  logStreamingOption: STREAM_ON
  logging: CLOUD_LOGGING_ONLY
